### ISSUE TITLE
enum constant "MAIN" isn't defined in GameType.java, and crashes when calling #getStatus(UUID)

### ISSUE THREAD

**Issue by aelteria** [HypixelDev/PublicAPI#335]
This occurs when the player referenced on HypixelAPI#getStatus(UUID) is in the Main Lobby.

Full trace:
java.lang.IllegalArgumentException: No enum constant net.hypixel.api.util.GameType.MAIN
	at java.lang.Enum.valueOf(Unknown Source)
	at net.hypixel.api.util.GameType.valueOf(GameType.java:3)
	at net.hypixel.api.adapters.GameTypeTypeAdapter.deserialize(GameTypeTypeAdapter.java:26)
	at net.hypixel.api.adapters.GameTypeTypeAdapter.deserialize(GameTypeTypeAdapter.java:12)
	at com.google.gson.TreeTypeAdapter.read(TreeTypeAdapter.java:58)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:95)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:183)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:95)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:183)
	at com.google.gson.Gson.fromJson(Gson.java:805)
	at com.google.gson.Gson.fromJson(Gson.java:770)
	at com.google.gson.Gson.fromJson(Gson.java:719)
	at com.google.gson.Gson.fromJson(Gson.java:691)
	at net.hypixel.api.HypixelAPI.lambda$null$0(HypixelAPI.java:254)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:222)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:164)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:139)
	at net.hypixel.api.HypixelAPI.lambda$get$1(HypixelAPI.java:249)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

**Comment by JustinScruggs1** [comment]
[i a​m 11 years old](https://www.youtube.com/channel/UCvgGyy3WhqZInGrCX_oBzXQ)

**Comment by aelteria** [comment]
closed: doxxing attempt
